### ISSUE TITLE
[Orga] Konzept Prüfungsform überdenken (Praktikum)

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden-CampusMinden/Prog2-Lecture#438]
Aktuell gibt es eine Performanzprüfung (Praktikum, Klausur). Dabei wird das Praktikum unterteilt in Konzeptblätter und Dungeonaufgaben. Die Abnahmen im Praktikum sind zeitlich recht eng.

Das Deploy-to-Abgabe-Konzept sollte im Praktikum für etwas Entspannung sorgen. Allerdings ist aktuell fraglich, ob wir das wirklich flächendeckend umsetzen können.

Die Kahoots sind bereits von vielen durchgearbeitet, d.h. die kann man in der Sprechstunde nicht mehr richtig einsetzen. (Wenn der Pool an Fragen erst einmal groß genug ist, kann man hier splitten.)

---

Idee: 

- Die Konzeptaufgaben werden im Flipped-Teil der Vorlesung ("Sprechstunde") besprochen. Möglich wäre entweder das gemeinsame Durcharbeiten dieser Aufgaben in Kleingruppen mit Präsentation der Lösungen im Plenum oder aber eine Abgabe vor der Sprechstunde und dann die Präsentation in Kleingruppen mit Peer-Feedback. Dies könnte entweder mit Testat oder freiwillig sein.
- Die Dungeonaufgaben ergeben ein Testat statt einer Note. Dabei müsste die Schwelle bei 80% o.ä. liegen, damit ausreichend gearbeitet wird. 
- Die Klausur wird in zwei kleineren Teilen geschrieben (erster Zeitraum) oder in einer längeren Sitzung (zweiter Zeitraum).

---

Idee:

Aufgaben für Notenstufen definieren: 4.0 (Minimum), 3.0, 2.0 (gut), 1.0 (sehr gut)

- Jede Woche Vorstellung des Fortschritts => Punkte für Vorstellung, Punkte für Fortschritt (eher formal)
  - ggf. Teilen der Klasse: jede Woche immer nur die Hälfte
- Am Ende: Vorstellung der Aufgaben/Lösungen:
  - Alle Aufgaben bis best. Stufe gelöst für allg. Note
  - Feinabstufung für Code-Qualität, Teilaspekte, Vorstellung: Teilnote hoch/runter
-  Keine extra Klausur

Prüfungsform? Parcours?

Evtl. analog zu KI: Aufgaben bis ein Monat vor Ende, dort auch Abgabe und Bewertung. Zusätzliche Aufgabe im letzten Monat zum Aufbessern der Punktebilanz/Note.

---

Idee: 

Aktuell erscheint eine Parcours-Prüfung mit 3 bewerteten Abgaben (inkl. Vorstellung im Praktikum) sowie einer kurzen Prüfung sinnvoll (3x 20%, 1x 40%). Dazu wöchentliche Abgaben per D2G und Diskussion in Peer-Groups im Praktikum.

--- 

Idee:

Parcoursprüfung mit 11 Stationen: 10x Blatt, 1x Klausur

Abgaben analog zu Testat: Es gibt 10 Blätter. Für jedes mit einem bestimmten Umfang bearbeitetes Blatt (60%? 70%) gibt es **1P**, in Summe kann man 10P erreichen. Es gibt eine schriftliche Prüfung am Ende des Semesters mit 100P. Der Gesamtnotenspiegel könnte 100P = 100% sein, d.h. die Punkte aus dem Praktikum sind "Bonuspunkte".

**Comment by cagix** [comment]
@AMatutat Was denkst Du?

**Comment by AMatutat** [comment]
Die Idee, die Konzeptaufgaben in der Sprechstunde zu besprechen finde ich gar nicht so schlecht. 
Brauchst du die Zeit aber nicht eigentlich, um Fragen zu beantworten?
Könnten wir das Tutorium für die Konzeptaufgaben nutzen? 

> Die Dungeonaufgaben ergeben ein Testat statt einer Note.

Davon bin ich hingegen kein großer Fan. 
Verschwindet unsere Praktika-Note dann nicht?

**Comment by cagix** [comment]
> Die Idee, die Konzeptaufgaben in der Sprechstunde zu besprechen finde ich gar nicht so schlecht. Brauchst du die Zeit aber nicht eigentlich, um Fragen zu beantworten? Könnten wir das Tutorium für die Konzeptaufgaben nutzen?

ja, ich brauche in der sprechstunde zeit für fragen. aber in pm ist das vor allem (immer noch) organisatorisch und gehört dort irgendwie nicht richtig hin, und in anderen modulen haben die studis kaum fragen. 

und da die quizzes (a) zu einfach und (b) bereits vorher gemacht wurden, wäre das eine gute ergänzung, d.h. in der sprechstunde würde man dann gemeinsam zu dem thema inhaltlich arbeiten.

es müsste nur sichergestellt sein, dass die leute auch mitmachen, weil die konzeptaufgaben ja die inhaltlichen themen einüben sollen. wenn man das freiwillig stellen würde (was ich gern täte), dann würden nur noch die fleissigen das machen und die, die es bräuchten, würden maximal mitpinseln. 


> > Die Dungeonaufgaben ergeben ein Testat statt einer Note.
> 
> Davon bin ich hingegen kein großer Fan. Verschwindet unsere Praktika-Note dann nicht?

Hach, ich schwanke immer hin und her. Hatte heute früh mit Jan gesprochen und fand, dass ein Testat eine relativ freie Lösung wäre. Und im Grunde ist es ja jetzt auch so: Man kann für die Dungeon-Aufgaben richtig viel machen für 2P, aber man kann auch nur das Minimum machen für die gleichen 2P. Das würde sich mit nem Testat nicht ändern.

Allerdings wäre dann die Gesamtnote nur noch eine Klausurnote. Das ist vielleicht nicht so prickelnd. Aber vielleicht könnte man 1..3 Aufgaben/Termine machen, wo die Punkte in eine Teilnote gehen?

**Comment by AMatutat** [comment]
Was für ein Testat o.ä spricht wäre, dass die Studis dann (vermutlich) weniger Punktefokusiert sind. Vielleicht kommen so die eigentlichen Inhalte wieder mehr in den Vordergrund und werden nicht erst 1 Woche vor der Klausur angeguckt.
