### ISSUE TITLE
[Aufgaben] Codeanalyse von Projektil ist bei Nahkampf unsinnig?

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden-CampusMinden/Prog2-Lecture#722]
Sowohl in der Aufgabe "Nahkampf" als auch in der Aufgabe "Fernkampf" wird eine Codeanalyse zum Projektil eingefordert. Bei "Nahkampf" erscheint das nicht wirklich sinnvoll?

**Comment by cagix** [comment]
@AMatutat Sag mal was dazu. Das ist Copy&Paste, oder?

**Comment by AMatutat** [comment]
Der Vorschlag von @Lena241 war damals (und ich finde den echt gut) das Nahkampf eigentlich auch nur Fernkampf (ein Projektil) ist, aber halt mit ganz wenig Reichweite. Mit dem Konzept lassen sich beide Kampfarten mit der selben Implementierung umsetzten. 

Für beides ist aber ein Verständnis von Projektilen wichtig. 
Und je nachdem welche Aufgabe man (zuerst) macht, muss man sich das anschauen.

**Comment by AMatutat** [comment]
> der Wirkung von Waffeln

Nom nom nom, Waffeln ... (hihihi) 

> Hmmm, dann ist aber die Frage, warum das zwei Aufgaben sind? Konzeptionell wäre das dann ja der selbe Unterbau, also außer "anderen Parametern" die selben Strukturen/Konzepte (ok, das ist jetzt zu stark verkürzt)?

Die Aufgaben unterscheiden sich im Detail. Ein Fernkampf-Skill verhält sich anders als ein Nahkampf Skill. Ein Pfeil könnt auf Distanz immer ungenauer werden, weil er abfällt. Ein Flummi prallt an Wänden ab etc. 
Und für den Nahkampf hast du ja schon Beispiele genannt. 

Das Basis-Konzept ist aber das selbe, das stimmt.

**Comment by cagix** [comment]
> > der Wirkung von Waffeln
> 
> Nom nom nom, Waffeln ... (hihihi)
> 
> > Hmmm, dann ist aber die Frage, warum das zwei Aufgaben sind? Konzeptionell wäre das dann ja der selbe Unterbau, also außer "anderen Parametern" die selben Strukturen/Konzepte (ok, das ist jetzt zu stark verkürzt)?
> 
> Die Aufgaben unterscheiden sich im Detail. Ein Fernkampf-Skill verhält sich anders als ein Nahkampf Skill. Ein Pfeil könnt auf Distanz immer ungenauer werden, weil er abfällt. Ein Flummi prallt an Wänden ab etc. Und für den Nahkampf hast du ja schon Beispiele genannt.

Dann würde ich die Nahkampfaufgabe vom Code-Review "subtrahieren" - das könnte mit dem Projektil gemacht werden, aber auch komplett anders. Fernkampf hat dagegen irgendwie immer das Projektil zwangsweise dabei. 

> 
> Das Basis-Konzept ist aber das selbe, das stimmt.

Das ist "gefährlich": Eigentlich sollen ja pro Aufgabe auch unterschiedliche Konzepte umgesetzt werden und nicht nur Parameter angepasst bzw. Ausprägungen leicht modifiziert werden. Wir würden ja auch keine freie Aufgabe mit noch mehr Monstern annehmen :) ... Gut, hier könnten Nah- und Fernkampf weit genug auseinander driften, aber es könnte auch wer auf die Idee kommen: Nahkampf ist einfach Fernkampf mit geringer Reichweite. Das wäre irgendwie zu einfach.

**Comment by cagix** [comment]
outdated.
