### ISSUE TITLE
[VL] Einstieg Dungeon überarbeiten

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden-CampusMinden/Prog2-Lecture#739]
Das [How-To Dungeon](https://github.com/Programmiermethoden-CampusMinden/Prog2-Lecture/blob/master/lecture/frameworks/dungeon.md) muss inhaltlich an die neue Codebasis angepasst werden.

- [ ] Codebasis analysieren
- [ ] Beispiel anpassen
- [ ] Unterlagen anpassen
- [ ] Video neu drehen

**Comment by AMatutat** [comment]
Soll ich mich mal hier rein Assigneen? Das How-To anzupassen fällt klar in meinen Aufgabenbereich. Das Video vermutlich eher in deinen.

**Comment by cagix** [comment]
done. kein dungeon in 2024.
