### ISSUE TITLE
[ORG] Praktikum überdenken, Rolle des PM-Dungeons

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden-CampusMinden/Prog2-Lecture#740]
Die Prüfungsergebnisse im S23 deuten stark darauf hin, dass das Programmieren im Dungeon im Praktikum den Studis zwar überwiegend mehr Spass macht (lt. Umfragen), aber dass die Studis die Inhalte der Veranstaltung nicht (freiwillig) im Praktikum anwenden und damit nur ungenügend lernen bzw. trainieren.

**Varianten**

- (a) Beibehaltung des Dungeons im Praktikum, aber wieder parallel "theoretische" (fachliche) Aufgaben einführen
- (b) Beibehaltung des Dungeons im Praktikum und Verbindung der Dungeon-Aufgaben mit den Inhalten der Veranstaltung  
- (c) Absetzen des Dungeons und Rückkehr zu den herkömmlichen reinen themenbezogenen/fachlichen Übungsaufgaben plus D2G

(a) hatten wir schon mal und haben es in S23 aufgelöst wegen der deutlich zu hohen Arbeitslast der Studis.
(b) bedeutet letztlich, das Ziel Self-paced Learning aufzugeben: Die Dungeon-Sachen werden realistisch nicht per D2G testbar sein, wenn man die Codebasis/Testbarkeit des Dungeons anschaut.
(c) muss auch im Licht der offenen Frage der Weiterentwicklung und Pflege des Dungeons betrachtet werden. Wir haben aktuell über einen Monat Refactoring investiert, und angesichts von Tickets wie https://github.com/Programmiermethoden/Dungeon/pull/858 stellt sich die Frage, wieviel Arbeit da noch notwendig wird und ob die realistisch neben der Lehre leistbar ist. Die direkten Vorteile dieser Variante wären das intensivere Üben der Veranstaltungsthemen sowie die Möglichkeit zum Wechsel der Sprache (Haskell, OCaml, Racket, Clojure, Rust) sowie eine Arbeitserleichterung (Wegfall der Maintenance des Frameworks für ein Framework).

Die Diskussion sollte zusammen mit der Diskussion um die Prüfungsform (#438) geführt werden. Aktuell erscheint eine Parcours-Prüfung mit 3 bewerteten Abgaben (inkl. Vorstellung im Praktikum) sowie einer kurzen Prüfung sinnvoll (3x 20%, 1x 40%). Dazu wöchentliche Abgaben per D2G und Diskussion in Peer-Groups im Praktikum.

Eventuell macht es auch Sinn, auf den Dungeon zu verzichten und die Studis direkt mit [libGDX](https://github.com/libgdx/libgdx) plus [gdx-liftoff](https://github.com/tommyettinger/gdx-liftoff) oder aber auch mit einem einfacheren Framework wie [**jMonkeyEngine**](https://github.com/jMonkeyEngine/jmonkeyengine) arbeiten zu lassen? Ursprünglich sollte der Dungeon den Studis eine einfache Basis bieten zum Start in ein eigenes Spiel, mittlerweile ist es aber ein Featuremonster mit nicht immer nachvollziehbaren Modellierungs- und Architekturentscheidungen geworden; zusätzlich ist der Dungeon ein Framework um ein anderes Framework herum (libGDX) und damit direkt abhängig von Entwicklungen dort. Diese Variante würde mir die Pflege des Dungeon sparen und den Studis trotzdem Game-based Learning ermöglichen. Auch der Wechsel zu anderen Sprachen wäre leicht(er). Es bliebe aber das Problem mit den inhaltlichen Aufgaben.

Edit: jMonkey scheint gut geeignet zu sein, basiert auf Ant/Maven und scheint den schrittweisen Aufbau eines eigenen Spiels gut zu unterstützen, ohne dass man noch zusätzlich "riesige" Strukturen (aka eigenes Framework) bereitstellen müsste? Zudem scheint damit such eine gute Verzahnung zu ADS möglich zu sein (Szenengraph, ...).

Edit: Potentielle Alternativen: [**jMonkeyEngine**](https://github.com/jMonkeyEngine/jmonkeyengine), [SquidLib](https://github.com/yellowstonegames/SquidLib), [litiengine](https://github.com/gurkenlabs/litiengine), https://github.com/FreeCol/freecol, https://github.com/00-Evan/shattered-pixel-dungeon, andere Game-Projekte von [awesome-java](https://github.com/akullpp/awesome-java)

--- 

Edit: Rückblickend hat den Studis das Programmieren im Dungeon wohl mehr Spass gemacht als das Bearbeiten normaler Übungsaufgaben. 

Dieses Vorgehen lässt sich aber kaum bis gar nicht mit den VL-Inhalten verzahnen (inhaltlich, zeitlich). Zusätzliche fachliche Aufgaben erhöhen den Workload. 

Zugleich hat kaum ein Studi-Team wirklich am Ende ein interessantes Spiel programmiert - die meisten hatten nur ein Level und nur leicht von den Vorgaben abgewandelte Monster, es fehlt an Spielideen. Die fortgeschritteneren hatten vielleicht interessantere Monster, aber so richtig Spielideen oder Quests o.ä. sind eigentlich nirgendwo erarbeitet worden.

Wenn man grob bei der Idee Gamification bleiben möchte, könnte man (b) weiterentwickeln: Die Studis sollen kein eigenes Spiel mehr entwickeln, sondern **auf der Basis eines existierenden Spiels gezielt bestimmte Modifikationen und Erweiterungen erstellen**. Zusätzlich können möglicherweise ähnlich wie bei **Escape Rooms** gezielt **Rätsel in Form von Spielsituationen gestellt werden, die nur durch Programmcode zu lösen sind**? Dabei könnten sich dann gezielt die fachlichen Inhalten aus der VL einbauen lassen.

Abwägung Basis:
- PM-Dungeon
    - (+) Weiternutzung des Frameworks
    - (-) Für die Nutzung müsste zunächst ein kohärentes Spiel aufgebaut werden 
    - (-) Wenig Vertrauen in die Codebasis (Art der Entwicklung, Verfügbarkeit von Tests, Qualität von Code/Dokumentation/Strukturen/Konzepten)
    - (-) Dungeon: Framework um ein anderes Framework (libGDX) herum, beide recht umfangreich und verwoben 
    - (-) Änderungen im Dungeon dürfen den DSL-Teil nicht kaputt machen
- ShPD (https://github.com/00-Evan/shattered-pixel-dungeon)
    - (+) Fertiges Spiel mit kohärenten Leveln, Aufgaben und Quests, hohe optische Qualität 
    - (+) Erweiterungen einfach realisierbar 
    - (+) Escape-Rooms vermutlich leicht zu ergänzen 
    - (+) kommerziell erfolgreich eingesetzt: Entwickler achtet hoffentlich auf Lauffähigkeit auf allen relevanten Systemen
    - (-) Strukturen "fremd" und nicht beeinflussbar 
    - (-) Eigene Entwicklungen entweder durch Fork und Änderungen in der Codebasis (eigener lokaler Master-Branch neben dem von ShPD) oder durch Seitenprojekt mit Git-Submodule: ersteres problematisch bei Fortschritt des ShPD, häufiges Rebasing nötig, letzteres problematisch typische Git-Submodule-Issues
- Sonstiges Framework (Gurkenlabs,https://github.com/FreeCol/freecol)
    - (+) Einfacherer Aufbau direkt in Java/JDK und ohne libGDx
    - (-) Strukturen und Spiel fremd (Einarbeitung)
    -

**Comment by AMatutat** [comment]
Falls ich mich zu c) äußern darf:

- Ticket #858 bezieht sich auf das Dungeon-Projekt und nicht auf das Framework. Ich finde daher, dass es kein gutes Beispiel für das Problem ist. Um das Feature-Monster zu reduzieren, könnten wir für das Projektmanagement nur den `core` anbieten (dafür haben wir die Aufteilung schließlich vorgenommen). Dadurch wird das Framework wieder deutlich überschaubarer. Gab es seitens der Studierenden Beschwerden oder Kommentare, dass das Framework zu komplex ist?

Zu B):
Ich finde das selbstgesteuerte Lernen gut, dass die Studierenden sich mit einem "realen" Problem auseinandersetzen müssen und eigenständig überlegen müssen, welche Techniken für die Lösung hilfreich sein könnten. Wenn sich dies jedoch nicht positiv auf den Lernerfolg auswirkt, bringt es halt nichts. Die Frage ist auch, ob es eine Alternative gibt, die selbstgesteuertes Lernen in diesem Sinne ermöglicht und gleichzeitig den Lernerfolg sicherstellt.

Falls du das Dungeon nicht mehr für das selbstgesteuerte Lernen verwenden möchtest/kannst, ist es zumindest immer noch ein motivierendes Arbeitsumfeld.

**Comment by cagix** [comment]
@AMatutat Jetzt fühle ich mich gestalkt ;)

Alles in allem betrachtet: 

- Das Basteln eines Spiels hat den Leuten Spass gemacht (Umfrage, pers. Gespräch). Deutlich mehr Spass als klassische Übungsaufgaben.
- Der Einstieg in den Dungeon war für viele eine echte Hürde (Umfrage, pers. Gespräch), das lag zum Teil auch an der damals eher schrottigen Dokumentation (die jetzt besser ist). 
- Die Dungeon-Aufgaben ermöglichen im Prinzip, dass man sich die passenden Lösungstechniken raussucht (raussuchen muss) und anwendet. In der Praxis wollen die Leute aber nur möglichst schnell die Aufgabe abhaken und da wird dann oft einfach eine irgendwie halbwegs funktionierende Lösung hingedrechselt. Ich sehe im Moment aber auch keinen praktikablen Weg, hier etwas "sinnvolles" zu erzwingen: Dann bin ich nämlich relativ schnell bei (b) und dann ist das freie Konzept bzw. das _self-paced learning_ futsch. Die Ansätze mit der Unterstützung durch Lerntagebücher im S22 bzw. durch Konzeptskizzen im S23 würde ich beide als komplett fehlgeschlagen bezeichnen.
- ECS ist für die Leute im zweiten Semester ein Konzept, was offenbar viel zu weit weg vom typischen Horizont ist. 95% der Abgaben haben klassische OOP-Lösungen gebastelt und am ECS komplett vorbei gearbeitet und hatten hier deshalb mit diversen Schwierigkeiten zu kämpfen. Hier war unser Framework deshalb tatsächlich eher hinderlich. Bin mir nicht sicher, ob das mit einer tieferen Einführung in ECS-Konzepte besser werden würde.
- Die Leute sind erwachsen und für sich selbst verantwortlich. Aber Ende sollen sie bestimmte Dinge lernen - und möglichst nicht erst für die bzw. in der Klausur. Die Prüfungsergebnisse dieses Jahr waren so schlecht wie noch nie (deutlich). Klar, das kann auch mit am Jahrgang liegen, aber ich führe das zum Teil auf das Fehlen verbindlicher Aufgaben zu den Vorlesungsinhalten zurück.
- Der Dungeon hat einfach eine gewisse Komplexität erreicht und überschritten, die noch nebenbei wartbar erscheint. Es gibt richtige "schwarze Löcher", wo sich niemand mehr dran traut (Beispiel Level und Level-Generator). Es gibt genügend Stellen mit "historisch gewachsenen Strukturen", und die Diskussion in https://github.com/Programmiermethoden/Dungeon/pull/858 zeigt, dass es weiter munter "historisch wächst". Die Schwierigkeiten in  https://github.com/Programmiermethoden/Dungeon/issues/815, https://github.com/Programmiermethoden/Dungeon/issues/812, https://github.com/Programmiermethoden/Dungeon/issues/811 oder https://github.com/Programmiermethoden/Dungeon/issues/825 und auch https://github.com/Programmiermethoden/Dungeon/issues/846 sind ja nicht einfach nur schlichte Coding-Probleme - hier zeigen sich auch Lücken im grundlegenden Konzept. Zudem hängt die Kiste direkt von libGDX ab - ich "freue" mich schon auf den Tag, wo die irgendwas ändern.

Ich sage nicht, dass ich den Dungeon wegwerfen will. Ich habe mir nur für mich notiert, dass ich darüber nachdenken muss, wie ich das Praktikum für das Modul in Zukunft gestalte. Dieses Jahr hatten sie zwar Programmierpraxis, aber deutlich zu wenig Inhalte angewendet.

Der Einstieg in den Dungeon mit dem ECS scheint für viele echt richtig komplex zu sein - und dann stellt sich die Frage, ob sie dann nicht mit einer eigenen Lösung direkt auf dem ganz untendrunter liegenden Framework besser fahren. Natürlich stellen sich dann sofort die ganzen Fragen nach Level und Game-Loop etc. ... Da sollte der Dungeon ja die Antwort drauf liefern.

**Comment by AMatutat** [comment]
> @AMatutat Jetzt fühle ich mich gestalkt ;)

I´m watching you. 

> Alles in allem betrachtet:
> 
> * Das Basteln eines Spiels hat den Leuten Spass gemacht (Umfrage, pers. Gespräch). Deutlich mehr Spass als klassische Übungsaufgaben.
> * Der Einstieg in den Dungeon war für viele eine echte Hürde (Umfrage, pers. Gespräch), das lag zum Teil auch an der damals eher lausigen Dokumentation (die jetzt deutlich besser ist). Aber eben auch am ECS-Konzept und einer relativ großen API.

Bessere Dokumentation und bessere Erläuterung des ECS-Konzeptes können hier teilweise helfen. Sich in "fremde" Codebasen einarbeiten ist nie einfach, wird es auch nie sein. Eine gewisse Hürde wird es so immer geben.

> * Die Dungeon-Aufgaben ermöglichen im Prinzip, dass man sich die passenden Lösungstechniken raussucht (raussuchen muss) und anwendet. In der Praxis wollen die Leute aber nur möglichst schnell die Aufgabe abhaken und da wird dann oft einfach eine irgendwie halbwegs funktionierende Lösung hingedrechselt. Ich sehe im Moment aber auch keinen praktikablen Weg, hier etwas "sinnvolles" zu erzwingen: Dann bin ich nämlich relativ schnell bei (b) und dann ist das freie Konzept bzw. das _self-paced learning_ futsch. 

Man könnte hier das self-paced-learning etwas "abschwächen". Man mapt die Vorlesungsthemen mit den Praktikumsaufgaben, sagt also ganz klar "Diese Aufgabe löst du mit dieser Technik". Wann die welches Thema bearbeiten, ist denen wiederum freigestellt. Auch der Umfang der Lösung kann weiterhin recht offen bleiben. 
Bounty-Aufgaben für Bonuspunkte kann es auch weiterhin geben. 

> Die Ansätze mit der Unterstützung durch Lerntagebücher im S22 bzw. durch Konzeptskizzen im S23 würde ich beide als komplett fehlgeschlagen bezeichnen.

Hab ich befürchtet. Auf dem Papier finde ich die Idee gut, aber praktisch will es einfach nicht funktionieren. 

> * ECS ist für die Leute im zweiten Semester ein Konzept, was offenbar viel zu weit weg vom typischen Horizont ist. 95% der Abgaben haben klassische OOP-Lösungen gebastelt und am ECS komplett vorbei gearbeitet und hatten hier deshalb mit diversen Schwierigkeiten zu kämpfen. Hier war unser Framework deshalb tatsächlich eher hinderlich. Bin mir nicht sicher, ob das mit einer tieferen Einführung in ECS-Konzepte besser werden würde.

Ich weiß noch nicht wie relevant ich diesen Punkt finde. Schwierigkeiten gehören nunmal auch zum Job und es soll schließlich nicht "einfach" sein. Ob die Arten von Schwierigkeiten die richtigen sind, ist die andere Frage. Ich könnte jetzt die "In der richtigen Welt" Keule rausholen und sagen, dass man in der Wirtschaft vermutlich eh nie was komplett neues programmiert sondern sich immer in bestehende Konzepte und Konstrukte einordnen muss. Weiß nur nicht ob das zweite Semester schon der Punkt dafür ist. 

Theoretisch existiert auch noch das alte OOP-Dungeon. Weiß nur nicht wie glücklich man damit wird.

> * Die Leute sind erwachsen und für sich selbst verantwortlich. Aber Ende sollen sie bestimmte Dinge lernen - und möglichst nicht erst für die bzw. in der Klausur. Die Prüfungsergebnisse dieses Jahr waren so schlecht wie noch nie (deutlich). Klar, das kann auch mit am Jahrgang liegen, aber ich führe das zum Teil auf das Fehlen verbindlicher Aufgaben zu den Vorlesungsinhalten zurück.

Wie immer, wird bestimmt nicht nur am Dungeon liegen, aber halt auch am Dungeon. 

> * Der Dungeon hat einfach eine gewisse Komplexität erreicht und überschritten, die noch nebenbei wartbar erscheint. Es gibt richtige "schwarze Löcher", wo sich niemand mehr dran traut (Beispiel Level und Level-Generator). 

Die schwarzen Löcher müssten gestopft werden, da bin ich bei dir (und die stehen ja tatsächlich auch aktiv auf dem Plan). 


> Es gibt genügend Stellen mit "historisch gewachsenen Strukturen", und die Diskussion in [[GAME] make `QuizQuestion` extend `Task`  Dungeon#858](https://github.com/Programmiermethoden/Dungeon/pull/858) zeigt, dass es weiter munter "historisch wächst". 

Ich finde den PR immernoch doof als Beispiel für weiter historisch wachsende Strukturen im PM-Dungeon. Im Framework selbst sehe ich sowas nicht mehr dazukommend. Wir sind aktiv dabei die alten Strukturen an das neue System anzupassen (z.B [[GAME] refactor LevelManger into LevelSystem](https://github.com/Programmiermethoden/Dungeon/pull/769)) 

> Die Schwierigkeiten in  [[GAME] Doppelte Assets Dungeon#815](https://github.com/Programmiermethoden/Dungeon/issues/815), [[GAME] MeleeAI in MonsterBuilder verursacht NullPointerException Dungeon#812](https://github.com/Programmiermethoden/Dungeon/issues/812), [[GAME] Spiel friert ein, Programm reagiert nicht mehr Dungeon#811](https://github.com/Programmiermethoden/Dungeon/issues/811) oder [[GAME] Existenz ob Components existieren erst zur Laufzeit prüfen Dungeon#825](https://github.com/Programmiermethoden/Dungeon/issues/825) und auch [[GAME] Richtigen Umgang mit negativen `DamageModifier` überdenken Dungeon#846](https://github.com/Programmiermethoden/Dungeon/issues/846) sind ja nicht einfach nur schlichte Coding-Probleme - hier zeigen sich auch Lücken im grundlegenden Konzept. 

Einiges davon sind tatsächlich schlichte Coding-Probleme, anderes sind kleinere Konzept Entscheidungen. Ich will nochmal festhalten, dass wir aktuell das Framework nur noch geringfügig um neue Features erweitern (eigentlich nur Feature die wir für das Projekt brauchen), das bedeutet wir packen grade aktiv diese ganzen "kleinigkeiten" an. 
Natürlich werden solche Probleme immer mal wieder auftreten und lassen sich nie 100% vermiden (teilweise sieht man Sachen nach 2Jahren auch einfach anders) 
Wir sollten aber die Studis nicht vergessen, die richtig gute Lösungen und Verbesserungen am Framework beigesteuert haben. 


> Zudem hängt die Kiste direkt von libGDX ab - ich "freue" mich schon auf den Tag, wo die irgendwas ändern.

Da bin ich entspannt, wir müssen mit einer neuen libGDX version nicht mitziehen, wenn wir nicht wollen. 


> Ich sage nicht, dass ich den Dungeon wegwerfen will. Ich habe mir nur für mich notiert, dass ich darüber nachdenken muss, wie ich das Praktikum für das Modul in Zukunft gestalte. Dieses Jahr hatten sie zwar Programmierpraxis, aber deutlich zu wenig Inhalte angewendet.

Sind ja grundsätzlich legitime Gedanken, auch wenn ich nicht jeder Schlussfolgerung zustimme. Ich verteidige hier nur mein Baby, was du daraus machst bleibt ja bei dir.

> Der Einstieg in den Dungeon mit dem ECS scheint für viele echt richtig komplex zu sein - und dann stellt sich die Frage, ob sie dann nicht mit einer eigenen Lösung direkt auf dem ganz untendrunter liegenden Framework besser fahren. Natürlich stellen sich dann sofort die ganzen Fragen nach Level und Game-Loop etc. ... Da sollte der Dungeon ja die Antwort drauf liefern.

**Comment by cagix** [comment]
> > * Der Einstieg in den Dungeon war für viele eine echte Hürde (Umfrage, pers. Gespräch), das lag zum Teil auch an der damals eher lausigen Dokumentation (die jetzt deutlich besser ist). Aber eben auch am ECS-Konzept und einer relativ großen API.
> 
> Bessere Dokumentation und bessere Erläuterung des ECS-Konzeptes können hier teilweise helfen. Sich in "fremde" Codebasen einarbeiten ist nie einfach, wird es auch nie sein. Eine gewisse Hürde wird es so immer geben.

Darf es auch und soll es auch. Einarbeitung, Doku lesen, ..., alles okay.

Die Fragen hier konkret in PM sind aber: Erzwingt das Framework eine bestimmte Denkart, die zu dem eben grad im ersten Semester gelernten Muster quer liegt bzw. für die man evtl. bereits etwas mehr Erfahrung haben müsste? Wird mich das Framework von der Struktur und Denkweise eher bei meinem Ziel (Programmiererfahrung zu sammeln, ein Spiel zu erstellen) unterstützen oder eher behindern? In welchem Verhältnis stehen der Aufwand für die Einarbeitung in ein Framework o.ä. und das Verstehen des dortigen Denkweges zu den eigentlichen Inhalten/Aufgaben/Lösungen? 


> Man könnte hier das self-paced-learning etwas "abschwächen". Man mapt die Vorlesungsthemen mit den Praktikumsaufgaben, sagt also ganz klar "Diese Aufgabe löst du mit dieser Technik". Wann die welches Thema bearbeiten, ist denen wiederum freigestellt. Auch der Umfang der Lösung kann weiterhin recht offen bleiben. Bounty-Aufgaben für Bonuspunkte kann es auch weiterhin geben.

Hatten wir ja schon mal, hat auch nur so _meh_ funktioniert. Ich erinnere mich an Generics, wo eigentlich keiner so richtig verstanden hatte, was ich von den Studis will ;) ... 

Und es macht den Spaß deutlich komplexer: Die VL-Themen hängen voneinander ab, die Dungeon-Aufgaben ebenso untereinander. Wenn man jetzt noch die VL-Themen/-Techniken mit in die Dungeon-Aufgaben reinmixt, kann es schnell spannend werden.


> > * ECS ist für die Leute im zweiten Semester ein Konzept, was offenbar viel zu weit weg vom typischen Horizont ist. 95% der Abgaben haben klassische OOP-Lösungen gebastelt und am ECS komplett vorbei gearbeitet und hatten hier deshalb mit diversen Schwierigkeiten zu kämpfen. Hier war unser Framework deshalb tatsächlich eher hinderlich. Bin mir nicht sicher, ob das mit einer tieferen Einführung in ECS-Konzepte besser werden würde.
> 
> Ich weiß noch nicht wie relevant ich diesen Punkt finde. Schwierigkeiten gehören nunmal auch zum Job und es soll schließlich nicht "einfach" sein. Ob die Arten von Schwierigkeiten die richtigen sind, ist die andere Frage. Ich könnte jetzt die "In der richtigen Welt" Keule rausholen und sagen, dass man in der Wirtschaft vermutlich eh nie was komplett neues programmiert sondern sich immer in bestehende Konzepte und Konstrukte einordnen muss. Weiß nur nicht ob das zweite Semester schon der Punkt dafür ist.

Siehe oben. Herausforderung darf und soll sein. Und ja, man wird (fast) immer nur in bestehenden Strukturen herumwursteln. Die Frage ist nur: Was will ich den Leuten vermitteln, was sollen sie lernen? Das ist dieses Semester im Praktikum komplett untergegangen, das Getöse um das Framework und wie benutze ich das richtig war einfach zu laut. 


> > * Die Leute sind erwachsen und für sich selbst verantwortlich. Aber Ende sollen sie bestimmte Dinge lernen - und möglichst nicht erst für die bzw. in der Klausur. Die Prüfungsergebnisse dieses Jahr waren so schlecht wie noch nie (deutlich). Klar, das kann auch mit am Jahrgang liegen, aber ich führe das zum Teil auf das Fehlen verbindlicher Aufgaben zu den Vorlesungsinhalten zurück.
> 
> Wie immer, wird bestimmt nicht nur am Dungeon liegen, aber halt auch am Dungeon.

Wir reden halt über ein zweites Semester, da ist Selbstdisziplin und -strukturierung eben noch nicht wirklich in ausreichendem Maß ausgeprägt. Meine Erkenntnis ist, dass ich wieder inhaltliche Aufgaben verpflichtend einführen muss. Die Frage ist nur: Parallel zum Dungeon, gemischt mit dem Dungeon, statt dem Dungeon?



> Natürlich werden solche Probleme immer mal wieder auftreten und lassen sich nie 100% vermiden (teilweise sieht man Sachen nach 2Jahren auch einfach anders) Wir sollten aber die Studis nicht vergessen, die richtig gute Lösungen und Verbesserungen am Framework beigesteuert haben.

Das liegt in der Natur der Sache. Allerdings habe ich (obwohl ich formal gar keinen Zeitanteil im Projekt habe) in den letzten Monaten ziemlich deutlich Zeit in das Projekt gesteckt und ich erkenne im Moment nicht, dass sich das ändern wird. Und ich habe ja eigentlich nur Reviews gemacht und Diskussionen angestoßen und nach Alternativkonzepten mitgesucht. Wenn das Projekt erstmal ausgelaufen ist und die Leute weg sind und der Spaß komplett auf meine Uhr geht, dann muss ich ja auch noch den Code selbst schreiben. Das sehe ich im Moment einfach nicht.


> 
> > Zudem hängt die Kiste direkt von libGDX ab - ich "freue" mich schon auf den Tag, wo die irgendwas ändern.
> 
> Da bin ich entspannt, wir müssen mit einer neuen libGDX version nicht mitziehen, wenn wir nicht wollen.

Das kannst Du ein oder zweimal machen, vielleicht ein oder zwei Jahre. Danach ist das komplett weggedriftet und Du kommst nie wieder dran. Meine Erfahrung sagt ganz klar: Updaten, wenn es neue Versionen gibt und halt dann den Code mit kleinen Schritten anpassen. Das kann ziemlich schnell den Kipp-Punkt erreichen.

**Comment by AMatutat** [comment]
> Wenn das Lernspiel nicht rechtzeitig fertig wird, dann auch ganz ohne Dungeon.

Dungeon traurig...

**Comment by cagix** [comment]
> > Wenn das Lernspiel nicht rechtzeitig fertig wird, dann auch ganz ohne Dungeon.
> 
> Dungeon traurig...

@AMatutat es liegt in deiner hand - du kannst dich gern beteiligen.
