### ISSUE TITLE
VL: Diskussion von "Conventional Commits"

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden-CampusMinden/Prog2-Lecture#768]
Im Zuge der Git-Einheiten könnte man über [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) sprechen. Das ist eine leichtgewichtige Konvention zum Erstellen von Git-Commit-Kommentaren und erscheint in der Praxis relativ nützlich.

Ergänzung zur Folie zu den Git-Commit-Kommentaren.

https://github.com/conventional-commits/conventionalcommits.org

**Comment by AMatutat** [comment]
Finn hat mir mal https://gitmoji.dev gezeigt.
Musste ich irgendwie dran denken als ich `<type>[optional scope]: <description>` gesehen habe. 
Emojis für `<type>` einsetzen....

Man muss mit der Zeit gehen oderso

**Comment by cagix** [comment]
> Finn hat mir mal https://gitmoji.dev gezeigt. Musste ich irgendwie dran denken als ich `<type>[optional scope]: <description>` gesehen habe. Emojis für `<type>` einsetzen....
> 
> Man muss mit der Zeit gehen oderso

auweia. sprache ist schon oft nicht eindeutig (genug), mit diesem emoji-mist will ich da gar nicht erst anfangen - fragst du drei leute zu einem emoji, kriegst du vier antworten, was das ding wohl bedeuten könnte.

**Comment by cagix** [comment]
wäre auch eine idee für eine challenge (=> sprechstunde)
