### ISSUE TITLE
VL: Screenshot IntelliJ/Gradle-Tasks in HowTo-Dungeon veraltet

### ISSUE THREAD

**Issue by tgrothe** [Programmiermethoden-CampusMinden/Prog2-Lecture#867]
Diese Abbildung stimmt nun nicht mehr, weil der Dojo-Run-Task umbenannt wurde:

https://github.com/Programmiermethoden-CampusMinden/Prog2-Lecture/blob/78e543b5cef346ab914e47465553106e91c77c96/lecture/frameworks/dungeon.md?plain=1#L175

Das folgt aus #860

**Comment by cagix** [comment]
richtig. dummerweise kriege ich keinen besseren screenshot hin, bevor devdungeon und dojodungeon nicht im selben repo sind - bis dahin ist einer der beiden veraltet.

an sich sollte das aber erstmal kein problem sein, da auf den aufgabenblättern die korrekten starter angegeben sind.

**Comment by tgrothe** [comment]
> an sich sollte das aber erstmal kein problem sein,

Ok :D
